---
- name: Set NCHC CentOS Stream repo manually
  copy:
    dest: /etc/yum.repos.d/CentOS-Stream-BaseOS.repo
    content: |
      [baseos]
      name=CentOS Stream 9 - BaseOS
      baseurl=https://free.nchc.org.tw/centos-stream/9-stream/BaseOS/$basearch/os/
      enabled=1
      gpgcheck=0

- name: Set NCHC CentOS Stream AppStream repo
  copy:
    dest: /etc/yum.repos.d/CentOS-Stream-AppStream.repo
    content: |
      [appstream]
      name=CentOS Stream 9 - AppStream
      baseurl=https://free.nchc.org.tw/centos-stream/9-stream/AppStream/$basearch/os/
      enabled=1
      gpgcheck=0

- name: Clean and rebuild yum cache
  shell: |
    dnf clean all
    dnf makecache
  args:
    warn: false

- name: Install required packages
  dnf:
    name: ["mysql-server", "python3-PyMySQL"]
    state: present

- name: Start and enable mysqld
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Get temporary MySQL root password (may fail if not initial install)
  shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: mysql_temp_password
  failed_when: false
  changed_when: false

- name: Set MySQL root password (initial or re-apply)
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_password: "{{ mysql_temp_password.stdout | default(mysql_root_password) }}"
    check_implicit_admin: true
    priv: "*.*:ALL,GRANT"
    state: present

