---
- name: Include Ubuntu tasks
  include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('24.04', '==')

- name: Include CentOS tasks
  include_tasks: centos.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '9'

