---
- name: Install required packages
  apt:
    name: ["mysql-server", "python3-pymysql"]
    state: present
    update_cache: yes

- name: Start and enable MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set MySQL root password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: true
    priv: "*.*:ALL,GRANT"
    state: present

