- name: Install required packages
  apt:
    name: ['wget', 'lsb-release', 'gnupg']
    state: present
    update_cache: yes

- name: Download MySQL APT config
  get_url:
    url: https://dev.mysql.com/get/mysql-apt-config_0.8.29-1_all.deb
    dest: /tmp/mysql.deb

- name: Install MySQL APT config
  apt:
    deb: /tmp/mysql.deb
    state: present

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Start and enable MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set MySQL root password
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: true
    priv: "*.*:ALL,GRANT"
    state: present

