---
- name: This is to add user on instances
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - set_fact:
      userpass: "{{ lookup('cypher','secret=secret/userpass') }}"

  - name: Add a user
    user:
      name: "{{ morpheus['customOptions']['username'] }}"
      password: "{{ userpass }}"
      state: present
  
  - debug:
        msg: "{{ lookup('cypher','secret=secret/userpass') }}"

  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      
  
  - name: Add sudoers users to wheel group
    user:
      name: "{{ morpheus['customOptions']['username'] }}"
      groups: wheel
      append: yes
      state: present
      createhome: yes
