---
- hosts: localhost
  gather_facts: yes

  tasks:
    - set_fact: 
        folder_size: "3"

    - set_fact:
        folder_plc: "{{ folder_size | int  - 1 }}"
    
    - debug:
        var:  "{{ folder_plc | int }}" 