---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
    - apt: "name={{ item }} state=present"
      with_items:
        - git
        - wget
        - curl
        - vim
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    
    - yum: "name={{ item }} state=present"
      with_items:
        - git
        - wget
        - curl
        - vim
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
