---
- hosts: all
  gather_facts: true
  tasks:
    - name: Update Tags on VMs
      vmware.ansible_for_nsxt.nsxt_vm_tags:
        hostname: "10.32.23.8"
        username: admin
        password: "{{ lookup('cypher','secret=secret/nsxt3') }}"
        validate_certs: False
        virtual_machine_display_name: "{{ morpheus['server']['hostname'] }}"
        remove_other_tags: False
        add_tags:
          - scope: my-scope
            tag: my-tag
      delegate_to: localhost