---
- name: This will pause the tasks for 20 minutes and then complete
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: the final countdown of 1200 seconds
    command: for i in `seq 1 1200`; do echo "sleeping $i second";sleep 1;done
