---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: ssr_vm
      assert:
        that:
          - morpheus.spec.config.customOptions.vmName is regex("^(?![0-9]+$)(?!-)[a-zA-Z0-9-]{4,15}(?<!-)$")
          - morpheus.spec.config.customOptions.vmName | length > 0
        fail_msg: |
          SSR input checks: FAIL. Unallowed characters in the name '{{ morpheus.spec.config.vmName }}'. Verify that the following rules for VM name are followed:
            - min. 4 and max. 15 characters
            - alphanumeric characteres and '-' are allowed
            - must not consist of all numeric characters
            - must not start or end with the '-' (dash)
        success_msg: "SSR input checks: Name validation passed."
    - name: ssr_vm | automation_tasks | check allowed VM password
      assert:
        that:
          - morpheus.spec.config.customOptions.vmPassword is regex("^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$")
          - morpheus.spec.config.customOptions.vmPassword | length > 0
        fail_msg: "SSR input checks: FAIL. Password '{{ morpheus.spec.config.vmPassword }}' is not strong enough. Please use minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character"
        success_msg: "SSR input checks: Password validation passed."